/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.videojuegolaberinto.vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Luzdary Fernandez
 */
public class GUILaberinto extends javax.swing.JFrame {
//     private PanelLaberinto panelLaberinto;

    /**
     * Creates new form GUILaberinto
     */
    public GUILaberinto() {
        initComponents();
    }

    public PanelLaberinto getPanelLaberinto() {
        return panelLaberinto;
    }
    
    public void escucharClick (MouseListener controlador){
        this.addMouseListener(controlador);
    }
    
    public void escucharTeclado(KeyListener controlador){
        this.addKeyListener(controlador);
    }

//    public PanelLaberinto getPanelLaberinto() {
//        return panelLaberinto;
//    }
//    
    
   
    
//    public void escuchar (ActionListener controlador){
//        btnRegre
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaberinto = new com.mycompany.videojuegolaberinto.vista.PanelLaberinto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLaberintoLayout = new javax.swing.GroupLayout(panelLaberinto);
        panelLaberinto.setLayout(panelLaberintoLayout);
        panelLaberintoLayout.setHorizontalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        panelLaberintoLayout.setVerticalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLaberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLaberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.videojuegolaberinto.vista.PanelLaberinto panelLaberinto;
    // End of variables declaration//GEN-END:variables
}
