/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.videojuegolaberinto.vista;

import com.mycompany.videojuegolaberinto.controlador.ControladorMenu;

/**
 *
 * @author Luzdary Fernandez
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu(ControladorMenu controlador) {
        initComponents();
        escuchar(controlador);
    }
    
    
    public void escuchar (ControladorMenu controlador){
      btnInstrucciones.addActionListener(controlador);
      btnHistoria.addActionListener(controlador);
      btnJugar.addActionListener(controlador);
      btnSalir.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistoria = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/botonHistoria.drawio.png"))); // NOI18N
        btnHistoria.setToolTipText("");
        btnHistoria.setActionCommand("historia");
        btnHistoria.setContentAreaFilled(false);
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/botonJugar.drawio.png"))); // NOI18N
        btnJugar.setToolTipText("");
        btnJugar.setActionCommand("jugar");
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/botonSalir.drawio.png"))); // NOI18N
        btnSalir.setToolTipText("");
        btnSalir.setActionCommand("salir");
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/botonInstrucciones.drawio.png"))); // NOI18N
        btnInstrucciones.setActionCommand("instrucciones");
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/MenuJuego.drawio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
