/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.videojuegolaberinto.vista;

import com.mycompany.videojuegolaberinto.controlador.ControladorLaberinto;
import com.mycompany.videojuegolaberinto.controlador.ControladorMenu;
import static java.awt.Color.blue;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Luzdary Fernandez
 */
public class PanelLaberinto extends javax.swing.JPanel {
    private ImageIcon fondo;
    private ControladorLaberinto controlador;
    

    /**
     * Creates new form PanelLaberinto
     */
    public PanelLaberinto() {
        initComponents();
        fondo= new ImageIcon("./src/main/resources/ImagenesJuego/PrimerLaberinto.drawio (1).png");
    }
    
    public void setControlador(ControladorLaberinto controlador){
        this.controlador=controlador; 
    }
    
    
    public void paint(Graphics g){
       super.paint(g);
       fondo.paintIcon(null, g, 0, 0);
       if(controlador!=null){
    Font fuente = new Font("Serif", Font.BOLD, 24);
    g.setFont(fuente);
    g.setColor(blue);
    g.drawString("x "+controlador.getC()+" y "+controlador.getF()+"valor "+controlador.getCelda(), controlador.getC(), controlador.getF());
           controlador.dibujar(g);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
